apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-custom-policies"
  namespace: "{{ .Release.Namespace }}"
data:
  {{- $files := .Files }}
  {{- range tuple "owners" }}
  {{ . }}: |-
    {{- $files.Get (printf "config/%s.yaml" .) | nindent 4}}
  {{- end }}