# Default values for kube-prometheus-stack are documented here:
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:

  prometheus:
    prometheusSpec:
      # The following values are changed from their default value of `true`
      # lets the Prometheus Operator handle ScrapeConfig, ServiceMonitor,
      # PodMonitor, and Probe resources in all namespaces, including the
      # "default" namespace that is used in our guestbook application, and
      # regardless of the labels on those resources.
      scrapeConfigSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false