{{- if and .Values.mutations.enabled .Values.mutations.propagateApplicationTeamLabel.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: propagate-application-team-label
  annotations:
    policies.kyverno.io/title: Propagate Application Team Label
    policies.kyverno.io/category: Argo
    policies.kyverno.io/severity: medium
    #policies.kyverno.io/subject: Label, Deployment
    #kyverno.io/kyverno-version: 1.11.1
    #kyverno.io/kubernetes-version: "1.27"
    policies.kyverno.io/description: >-
      Argo CD applications in our organization must specify a responsible team
      for development and operation in their `{{ .Values.teamLabel }}` label. This
      policy propagates the label to resources created by the application,
      including to Pod templates.
spec:
  background: false
  rules:
    - name: copy-app-team-label-to-instance
      match:
        any:
          - resources:
              kinds:
                - "*"
              selector:
                matchLabels:
                  argocd.argoproj.io/instance: "?*"
      context:
        - name: team
          apiCall:
            urlPath: '{{`/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/{{ request.object.metadata.labels."argocd.argoproj.io/instance" }}`}}'
            jmesPath: metadata.labels."{{ .Values.teamLabel }}"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              "{{ .Values.teamLabel }}": "{{`{{ team }}`}}"
    - name: copy-team-label-to-pod-template
      match:
        any:
          - resources:
              kinds:
                - CronJob
                - DaemonSet
                - Deployment
                - Job
                - ReplicaSet
                - StatefulSet
              selector:
                matchLabels:
                  "{{ .Values.teamLabel }}": "?*"
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                labels:
                  "{{ .Values.teamLabel }}": '{{`{{ request.object.metadata.labels."`}}{{ .Values.teamLabel }}{{`" }}`}}'
{{- end }}